#!/bin/bash

create='-c'
delete='-d'

if [[ $1 == $create ]]
then
	if [ -e $2 ]
	then
		echo "the file exists"
	else
		if touch $2
		then
			echo "$2 created"
		else
			echo "invalid name  or file path entered incorrect"
		fi
	fi
fi

if [[ $1 == $delete ]]
then
	if [ -e $2 ]
	then 
		if rm $2
		then
			echo " $2 deleted"
		else 
			echo "invalid name or file path entered incorrect"
		fi
	else 
		echo "file does not exist"
	fi
fi


